### ISSUE TITLE
after update to > 2.3.0 : the type change if not defined

### ISSUE THREAD

**Issue by mickadoua** [matrus2/dynamodb-stream-elasticsearch#16] opened 2019-07-10 20:19 UTC
After an update, the type is always "_doc"

Your documentation mention that if nothing is defined, the type & the index are equal to the table name.
It was true with 2.3.0 but not anymore. 

so, this generate this error during execution :
`Rejecting mapping update to [user] as the final mapping would have more than 1 type: [_doc, user]`

here the first item one my actual ES 
``` 
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "user",
        "_type": "user",
        "_id": "5c61386b-d7bb-4349-9655-1c81e222c060",
```

**Comment by matrus2** [comment] 2019-07-10 21:15
Hi,
Can see any changes to this part of functionality. Could you share an example event?

If you don't provide tablle name one is calculated by:
https://github.com/matrus2/dynamodb-stream-elasticsearch/blob/master/src/utils/table-name-from-arn.js

Here's also an integration test for it:
https://github.com/matrus2/dynamodb-stream-elasticsearch/blob/master/test/index.js#L96

**Comment by mickadoua** [comment] 2019-07-11 09:15
yes, its maybe is a dependency.
elasticsearch was updated to 16.1.1 on new release

**Comment by mickadoua** [comment] 2019-07-11 09:20
to reproduce this erreur, 
on 2.3.0, simply push an event
search all document, you will obtain => index: {YOUR_TABLE_NAME}  & type: {YOUR_TABLE_NAME} 
update to >= 2.3.2 
import the same event, 
this erreur will append:
`Rejecting mapping update to [user] as the final mapping would have more than 1 type: [_doc, YOUR_TABLE_NAME]`  

if you delete, the index, and import again with >= 2.3.2 you will obtain => index: {YOUR_TABLE_NAME}  & type: _doc

**Comment by matrus2** [comment] 2019-07-11 11:47
Hi,
Sorry, I tried, but can't reproduce it. 

Whichever version I pick, if the event is:
```{
  Records: [
    {
      eventID: 'f41d65c5ba9a67153994d2122275b05f',
      eventName: 'INSERT',
      eventVersion: '1.1',
      eventSource: 'aws:dynamodb',
      awsRegion: 'us-east-1',
      dynamodb: {
        ApproximateCreationDateTime: 1521459420,
        Keys: {
          url: {
            S: 'kale-pasros-253b536b-11'
          }
        },
        NewImage: {
          country: {
            S: 'US'
          },
          addedDate: {
            N: '1518103840119'
          },
          city: {
            S: 'New Shann'
          },
          company_id: {
            N: '1'
          },
          url: {
            S: 'kale-pasros-253b536b-1'
          },
          name: {
            S: 'kale pouros'
          }
        },
        SequenceNumber: '214656100000000005192507033',
        SizeBytes: 16430,
        StreamViewType: 'NEW_IMAGE'
      },
      eventSourceARN:
        'arn:aws:dynamodb:us-east-1:945413996076:table/Candidates/stream/2018-02-26T13:30:22.250'
    }
  ]
}```

Produce:

![image](https://user-images.githubusercontent.com/9248211/61048148-54f7b600-a3e1-11e9-8e18-9757c2a0e863.png)

Index and type is determined from arn:
`arn:aws:dynamodb:us-east-1:945413996076:table/Candidates/stream/2018-02-26T13:30:22.250` 
which in my case is `candidates`.

I'm not why type in your example are being mapped to an array `[_doc, YOUR_TABLE_NAME]` as function `table-name-from-arn` always returns one string. Could you provide an event, which produce this error?

**Comment by guilatrova** [comment] 2019-07-17 01:16
I'm having the same issue:

```
Error Error: MapperParsingException[mapping [_doc]]; nested: InvalidTypeNameException[mapping type name [_doc] can't start with '_'];
```

**Comment by matrus2** [comment] 2019-07-18 07:43
Please use 2.3.o for the time being, I will investigate that.

**Comment by all9lives** [comment] 2019-07-23 00:20
I'm seeing the same error after updating to `2.4.1`, even though I have been specifying the `type` and the `index`. 

```
Error Error: [illegal_argument_exception] Rejecting mapping update to [users] as the final mapping would have more than 1 type: [_doc, user]
```

In my case `index = users` and `type = user`

**Comment by matrus2** [comment] 2019-07-23 16:11
That's weird. I just setup simple configuration on AWS to reproduce the issue, but I couldn't. I see that `http-aws-es` has peer dependency set to `elasticsearch` to version `15.0.0`, so I can publish a patch to use this version ultimately.

To give more details I created a lambda with `2.3.0` and triggered few insert/modify events. After that I uploaded `2.4.1` and triggered few events as well. Everything seems to be working fine on my end. To properly debug the thing I would need a trace from CloudWatch with the event, which caused the error.

**Comment by matrus2** [comment] 2019-07-23 16:24
Let me know if `2.4.2` works for you

**Comment by all9lives** [comment] 2019-07-24 09:57
I'm still seeing the issue after updating to `2.4.2`. If I delete and re-create the index with Kibana, the issue goes away.  

Elasticsearch version is `6.3`, would that matter? I'm using AWS Elastic Search service and can potentially upgrade to 6.7.

**Comment by matrus2** [comment] 2020-03-19 15:39
closing if issue still exists, create a new one

**Closed by matrus2** 2020-03-19 15:39 UTC
